# Creating arrays from Existing Data - 7.1 - 7.2

In [21]:
import numpy as np

In [22]:
numbers = np.array([2, 3, 5, 7, 11])

In [23]:
print(type(numbers))

<class 'numpy.ndarray'>


In [24]:
print(numbers)

[ 2  3  5  7 11]


In [25]:
print(np.array([[1, 2, 3], [4, 5, 6]]))

[[1 2 3]
 [4 5 6]]


# Array Attributes

In [32]:
import numpy as np

In [33]:
integers = np.array([[1, 2, 3], [4, 5, 6]])

In [34]:
print(integers)

[[1 2 3]
 [4 5 6]]


In [35]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

In [38]:
print(floats)

[0.  0.1 0.2 0.3 0.4]


# determining an array's element type

In [37]:
print(integers.dtype)

int32


In [39]:
print(floats.dtype)

float64


# determining an arrays dimansions

In [40]:
print(integers.ndim)

2


In [41]:
print(floats.ndim)

1


In [42]:
print(integers.shape)

(2, 3)


In [44]:
print(floats.shape)

(5,)


In [45]:
print(integers.size)

6


In [46]:
print(integers.itemsize)

4


In [47]:
print(floats.size)

5


In [49]:
print(floats.itemsize)

8


# iterating through a multidimensional arrays elements

In [52]:
for row in integers:
    for column in row:
        print(column, end=' ')
    print()

1 2 3 
4 5 6 


In [53]:
for i in integers.flat:
    print(i, end=' ')

1 2 3 4 5 6 

# filling in arrays with specific values - 7.4

In [54]:
import numpy as np

In [55]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [56]:
print(np.ones((2, 4), dtype=int))

[[1 1 1 1]
 [1 1 1 1]]


In [57]:
print(np.full((3, 5), 13))

[[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]


# 7.5 Creating arrays from Ranges

In [58]:
import numpy as np

In [61]:
print(np.arange(5))

[0 1 2 3 4]


In [62]:
print(np.arange(5, 10))

[5 6 7 8 9]


In [63]:
print(np.arange(10, 1, -2))

[10  8  6  4  2]


# Creating floating point randes with linespace

In [66]:
print(np.linspace(0.0, 1.0, num=5))

[0.   0.25 0.5  0.75 1.  ]


# reshaping an array

In [68]:
print(np.arange(1, 21).reshape(4, 5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# 7.6 List vs. array Performance: Introducing %timeit

In [69]:
import random

In [74]:
%timeit rolls_list = \
   [random.randrange(1, 7) for i in range(0, 6_000_000)]

4.53 s ± 208 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [75]:
import numpy as np

In [76]:
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

53.6 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [77]:
%timeit rolls_array = np.random.randint(1, 7, 60_000_000)

657 ms ± 87.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [78]:
%timeit rolls_array = np.random.randint(1, 7, 600_000_000)

7.09 s ± 311 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [79]:
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)

71.7 ms ± 3.71 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)


# 7.7 array Operators

In [80]:
import numpy as np

In [91]:
numbers = np.arange(1, 6)

In [92]:
print(numbers)

[1 2 3 4 5]


In [93]:
print(numbers * 2)

[ 2  4  6  8 10]


In [94]:
print(numbers ** 3)

[  1   8  27  64 125]


In [95]:
print(numbers) # number is unchanged by arithmatic operators

[1 2 3 4 5]


In [96]:
numbers += 10

In [97]:
print(numbers)

[11 12 13 14 15]


# Arithmetic Operations Between Arrays

In [98]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [99]:
print(numbers2)

[1.1 2.2 3.3 4.4 5.5]


In [100]:
print(numbers * numbers2)

[12.1 26.4 42.9 61.6 82.5]


# # Comparing arrays

In [101]:
print(numbers)

[11 12 13 14 15]


In [102]:
print(numbers >= 13)

[False False  True  True  True]


In [103]:
print(numbers2)

[1.1 2.2 3.3 4.4 5.5]


In [104]:
print(numbers2 < numbers)

[ True  True  True  True  True]


In [105]:
print(numbers == numbers2)

[False False False False False]


In [106]:
print(numbers == numbers)

[ True  True  True  True  True]


# 7.8 NumPy Calculation Methods

In [107]:
import numpy as np

In [108]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [109]:
print(grades)

[[ 87  96  70]
 [100  87  90]
 [ 94  77  90]
 [100  81  82]]


In [110]:
print(grades.sum())

1054


In [111]:
print(grades.min())

70


In [112]:
print(grades.max())

100


In [113]:
print(grades.mean())

87.83333333333333


In [114]:
print(grades.std())

8.792357792739987


In [115]:
print(grades.var())

77.30555555555556


# # Calculations by Row or Column

In [116]:
print(grades.mean(axis=0))

[95.25 85.25 83.  ]


In [117]:
print(grades.mean(axis=1))

[84.33333333 92.33333333 87.         87.66666667]


# 7.9 Universal Functions

In [118]:
import numpy as np

In [119]:
numbers = np.array([1, 4, 9, 16, 25, 36])

In [120]:
print(np.sqrt(numbers))

[1. 2. 3. 4. 5. 6.]


In [121]:
numbers2 = np.arange(1, 7) * 10

In [122]:
print(numbers2)

[10 20 30 40 50 60]


In [123]:
print(np.add(numbers, numbers2))

[11 24 39 56 75 96]


# Broadcasting with Universal Functions

In [124]:
print(np.multiply(numbers2, 5))

[ 50 100 150 200 250 300]


In [125]:
numbers3 = numbers2.reshape(2, 3)

In [126]:
print(numbers3)

[[10 20 30]
 [40 50 60]]


In [127]:
numbers4 = np.array([2, 4, 6])

In [128]:
print(np.multiply(numbers3, numbers4))

[[ 20  80 180]
 [ 80 200 360]]


# 7.10 Indexing and Slicing

In [129]:
import numpy as np

In [130]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [131]:
print(grades)

[[ 87  96  70]
 [100  87  90]
 [ 94  77  90]
 [100  81  82]]


In [132]:
print(grades[0, 1])

96


# Selecting a Subset of a Two-Dimensional array’s Rows

In [133]:
print(grades[1])

[100  87  90]


In [134]:
print(grades[0:2])

[[ 87  96  70]
 [100  87  90]]


In [135]:
print(grades[[1, 3]])

[[100  87  90]
 [100  81  82]]


# Selecting a Subset of a Two-Dimensional array’s Columns

In [136]:
print(grades[:, 0])

[ 87 100  94 100]


In [137]:
print(grades[:, 1:3])

[[96 70]
 [87 90]
 [77 90]
 [81 82]]


In [138]:
print(grades[:, [0, 2]])

[[ 87  70]
 [100  90]
 [ 94  90]
 [100  82]]


# 7.11 Views: Shallow Copies

In [160]:
import numpy as np

In [161]:
numbers = np.arange(1, 6)

In [162]:
print(numbers)

[1 2 3 4 5]


In [163]:
numbers2 = numbers.view()

In [164]:
print(numbers2)

[1 2 3 4 5]


In [165]:
print(id(numbers))

1690759499280


In [166]:
print(id(numbers2))

1690758682064


In [147]:
numbers[1] *= 10

In [148]:
print(numbers2)

[ 1 20  3  4  5]


In [149]:
print(numbers)

[ 1 20  3  4  5]


In [150]:
numbers2[1] /= 10

In [151]:
print(numbers2)

[1 2 3 4 5]


In [152]:
print(numbers2)

[1 2 3 4 5]


# Slice Views

In [167]:
numbers2 = numbers[0:3]

In [168]:
print(numbers2)

[1 2 3]


In [169]:
print(id(numbers))

1690759499280


In [170]:
print(id(numbers2))

1690736906384


In [173]:
# print(numbers2[3]) index error

In [177]:
numbers[1] *= 10

In [178]:
print(numbers)

[1 0 3 4 5]


In [179]:
print(numbers2)

[1 0 3]


# 7.12 Deep Copies

In [180]:
import numpy as np

In [181]:
numbers = np.arange(1, 6)

In [182]:
print(numbers)

[1 2 3 4 5]


In [183]:
numbers2 = numbers.copy()

In [184]:
print(numbers2)

[1 2 3 4 5]


In [185]:
numbers[1] *= 10

In [186]:
print(numbers)

[ 1 20  3  4  5]


In [187]:
print(numbers2)

[1 2 3 4 5]


# 7.13 Reshaping and Transposing

In [188]:
import numpy as np

In [189]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [190]:
print(grades)

[[ 87  96  70]
 [100  87  90]]


In [191]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

In [192]:
print(grades)

[[ 87  96  70]
 [100  87  90]]


In [193]:
grades.resize(1, 6)

In [194]:
print(grades)

[[ 87  96  70 100  87  90]]


# flatten vs. ravel

In [195]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [196]:
print(grades)

[[ 87  96  70]
 [100  87  90]]


In [197]:
flattened = grades.flatten()

In [198]:
print(flattened)

[ 87  96  70 100  87  90]


In [199]:
print(grades)

[[ 87  96  70]
 [100  87  90]]


In [200]:
flattened[0] = 100

In [201]:
print(flattened)

[100  96  70 100  87  90]


In [202]:
print(grades)

[[ 87  96  70]
 [100  87  90]]


In [205]:
raveled = grades.ravel()

In [206]:
print(raveled)

[ 87  96  70 100  87  90]


In [207]:
print(grades)

[[ 87  96  70]
 [100  87  90]]


In [208]:
raveled[0] = 100

In [209]:
print(raveled)

[100  96  70 100  87  90]


In [210]:
print(grades)

[[100  96  70]
 [100  87  90]]


# Transposing Rows and Columns

In [211]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [212]:
print(grades)

[[100  96  70]
 [100  87  90]]


# Horizontal and Vertical Stacking

In [213]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])

In [214]:
print(np.hstack((grades, grades2)))

[[100  96  70  94  77  90]
 [100  87  90 100  81  82]]


In [215]:
print(np.vstack((grades, grades2)))

[[100  96  70]
 [100  87  90]
 [ 94  77  90]
 [100  81  82]]


# 7.14 Intro to Data Science: pandas Series and DataFrames

# Creating a Series with Default Indices

In [216]:
import pandas as pd

In [217]:
grades = pd.Series([87, 100, 94])

In [218]:
print(grades)

0     87
1    100
2     94
dtype: int64


# Creating a Series with All Elements Having the Same Value

In [219]:
pd.Series(98.6, range(3))

0    98.6
1    98.6
2    98.6
dtype: float64

# Accessing a Series’ Elements

In [220]:
print(grades[0])

87


# Producing Descriptive Statistics for a Series

In [221]:
print(grades.count())

3


In [222]:
print(grades.mean())

93.66666666666667


In [223]:
print(grades.min())

87


In [224]:
print(grades.max())

100


In [225]:
print(grades.std())

6.506407098647712


In [226]:
print(grades.describe())

count      3.000000
mean      93.666667
std        6.506407
min       87.000000
25%       90.500000
50%       94.000000
75%       97.000000
max      100.000000
dtype: float64


# Creating a Series with Custom Indices

#########PROJECT 5##############

# Create s Series with Default Indecies

In [5]:
import pandas as pd

In [6]:
grades = pd.Series([87, 100, 94])

In [7]:
print(grades[0])

87


# call in the built in series functions

In [9]:
print(grades.count())

3


In [10]:
print(grades.mean())

93.66666666666667


In [11]:
print(grades.min())

87


In [12]:
print(grades.max())

100


In [13]:
print(grades.std())

6.506407098647712


In [14]:
print(grades.describe())

count      3.000000
mean      93.666667
std        6.506407
min       87.000000
25%       90.500000
50%       94.000000
75%       97.000000
max      100.000000
dtype: float64


# Dictionary Initializers

In [15]:
grades = pd.Series({'Wally': 87, 'Eva': 100, 'Sam': 94})

In [16]:
print(grades)

Wally     87
Eva      100
Sam       94
dtype: int64


In [17]:
print(grades['Eva'])

100


In [18]:
print(grades.Wally)

87


In [19]:
print(grades.values)

[ 87 100  94]


In [20]:
print('Garrett Kopp')

Garrett Kopp
